#!/usr/bin/env bash
# Answer to questions on UDP and TCP
# Which statement is correct for the TCP box
# Which statement is correct for the UDP box
# Which statement is correct for the TCP worker

1
2
1
