#!/usr/bin/env bash
# displays numbers from 1 to 100 in list format.
# displays "FizzBuzz" when the number is a multiple of 3 and 5.
# displays "Fizz" when the number is a multiple of 3.
# displays "Buzz" when the number is a multiple of 5.
# otherwise, displays the number.

numb=1
while [ $numb -le 100 ]
do
  if (( numb % 3 == 0 && numb % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( numb % 3 == 0 ))
  then
    echo "Fizz"
  elif (( numb % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$numb"
  fi
  (( numb = numb + 1 ))
done
