#!/usr/bin/env bash
# This script prints "Best School" 10 times but prints "hi" after the 9th iteration

countn=1
string1="Best School"
string2="Hi"

while [ $countn -lt 10 ]
do
if [ $countn -eq 9 ]
then
	echo $string2
fi
	echo $string1

((countn = countn + 1))
done
