#!/usr/bin/env bash
# script that loops from 1 to 10 and:
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations

countn=1
string1="Best School"
string2="bad luck"
string3="good luck"

while [ $countn -lt 11 ]
do
	if [ $countn -eq 4 ]
	then
		echo $string2
	elif [ $countn -eq 8 ]
	then
		echo $string3
	else
		echo $string1
	fi

((countn = countn + 1))
done
