#!/usr/bin/env bash

# Script that displays the content of the current directory
# in a list format where only the part of the name after the first dash is displayed

list=$(ls)
for file in $list
do
    find "$file" | cut -d- -f2
done
